export default class Emote {
    static _Kappa_ = `Kappa`
    static _HeyGuys_ = `HeyGuys`
    static _LUL_ = `LUL`
    static _CoolStoryBob_ = `CoolStoryBob`
    static _4Head_ = `4Head`
    static _FrankerZ_ = `FrankerZ`
    static _Jebaited_ = `Jebaited`
    static _PJSalt_ = `PJSalt`
    static _NotLikeThis_ = `NotLikeThis`
    static _WutFace_ = `WutFace`
    static _VoHiYo_ = `VoHiYo`
    static _SeemsGood_ = `SeemsGood`
    static _ResidentSleeper_ = `ResidentSleeper`
    static _bleedPurple_ = `bleedPurple`
    static _TwitchUnity_ = `TwitchUnity`
    static _GivePLZ_ = `GivePLZ`
    static _CoolCat_ = `CoolCat`
    static _CurseLit_ = `CurseLit`
    static _DarkMode_ = `DarkMode`
    static _SMOrc_ = `SMOrc`
    static _PunchTrees_ = `PunchTrees`
    static _SirUwU_ = `SirUwU`
    static _SirMad_ = `SirMad`
    static _SirSword_ = `SirSword`
    static _SirSad_ = `SirSad`
    static _SirPrise_ = `SirPrise`
    static _StinkyGlitch_ = `StinkyGlitch`
    static _PowerUpL_ = `PowerUpL`
    static _PowerUpR_ = `PowerUpR`
    static _Getcamped_ = `Getcamped`
    static _GlitchNRG_ = `GlitchNRG`
    static _GayPride_ = `GayPride`
    static _EarthDay_ = `EarthDay`
    static _Squid_ = `Squid1 Squid3 Squid4`
    static _SirShield_ = `SirShield`
    static _GlitchCat_ = `GlitchCat`
}